linters:
  disable-all: false
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gofumpt
    - godot
    - gosec
    - makezero
    - misspell
    - wsl
    - gocritic
    - stylecheck
